version: "2"

services:
  api:
    command: nodemon services/api/main.js

  wareshub-git:
    command: nodemon services/wareshub-git/main.js


#  mongodb:
#    volumes:
#      - "./_dev/data/db:/data/db"
#    ports:
#      - "27017:27017"
